"""Core sale flow service — lifecycle management.

Implements: R01, R02, R03, R04, R05, R13, R14, R15, R16.
See sale_flow_line.py module docstring for the full requirements index.
"""

from odoo import api, fields, models, _
from odoo.tools import float_compare, float_is_zero


class SaleFlowService(models.AbstractModel):
    """Core service for sale.flow.line lifecycle management.

    Handles:
      * Creation of flow lines at order confirmation
      * Baseline snapshot storage
      * Reconciliation of post-confirmation changes
      * Reconfirmation baseline reset
      * Line deletion protection
    """

    _name = 'sale.flow.service'
    _description = 'Sale Flow Service'

    def _on_order_confirmed(self, order):
        """Create or update flow lines when a sale order is confirmed.

        At confirmation:
          1. Create sale.flow.line records for all relevant order lines.
          2. Store the commercial baseline (qty, price, discount, subtotal,
             description).
          3. Mark flow lines as confirmed.
          4. Link generated stock moves to the correct flow lines.

        If the order was previously cancelled and is being reconfirmed:
          1. Reset the commercial baseline.
          2. Treat the reconfirmed values as the new agreement.
          3. Clear previous invoice warning status.
        """
        FlowLine = self.env['sale.flow.line']

        for line in order.order_line:
            if line.display_type:
                # Skip section/note lines
                continue

            existing = line.flow_line_ids

            if existing:
                # Reconfirmation: reset baseline to current values
                self._reset_baseline(existing, line)
            else:
                # First confirmation: create new flow line
                flow_line = FlowLine.create(
                    self._prepare_flow_line_vals(order, line)
                )
                # Link any stock moves already generated by _action_launch_stock_rule
                moves = self.env['stock.move'].search([
                    ('sale_line_id', '=', line.id),
                    ('sale_flow_line_id', '=', False),
                ])
                if moves:
                    moves.with_context(skip_sale_flow_sync=True).write({
                        'sale_flow_line_id': flow_line.id,
                    })
                    flow_line.with_context(skip_sale_flow_sync=True).write({
                        'outgoing_move_ids': [(4, m.id) for m in moves],
                    })

    def _prepare_flow_line_vals(self, order, line):
        """Prepare values for a new sale.flow.line from a sale order line."""
        subtotal = line.price_unit * line.product_uom_qty * (1 - (line.discount or 0.0) / 100.0)
        is_rental = getattr(line, 'is_rental', False)

        vals = {
            'name': line.name or line.product_id.display_name,
            'sale_order_id': order.id,
            'sale_line_id': line.id,
            'product_id': line.product_id.id,
            'product_uom_id': line.product_uom_id.id,
            'sequence': line.sequence,
            # Baseline snapshot
            'confirmed_qty': line.product_uom_qty,
            'confirmed_unit_price': line.price_unit,
            'confirmed_discount': line.discount,
            'confirmed_subtotal': subtotal,
            'confirmed_description': line.name,
            'confirmed_at': fields.Datetime.now(),
            'confirmed_by_id': self.env.uid,
            # Operational
            'current_qty': line.product_uom_qty,
            'unit_price_effective': line.price_unit,
            # Product behavior
            'is_rental': is_rental,
            'is_sale': not is_rental,
            # State
            'state': 'confirmed',
            # Visibility: confirmed lines are visible to customer
            'visible_to_customer': True,
            # Audit
            'last_flow_update_at': fields.Datetime.now(),
            'last_flow_update_by_id': self.env.uid,
        }

        # Set hierarchy support (for Rental Set module)
        if hasattr(line, 'is_set_component') and line.is_set_component:
            vals['is_set_component'] = True
            if hasattr(line, 'set_parent_line_id') and line.set_parent_line_id:
                vals['set_parent_sale_line_id'] = line.set_parent_line_id.id
                # Find parent flow line
                parent_flow = line.set_parent_line_id.flow_line_ids[:1]
                if parent_flow:
                    vals['set_parent_flow_line_id'] = parent_flow.id
                    # Walk up to find root
                    root = parent_flow
                    while root.set_parent_flow_line_id:
                        root = root.set_parent_flow_line_id
                    vals['set_root_flow_line_id'] = root.id

        # Charge-only detection (e.g. delay lines, fee lines)
        if hasattr(line, 'is_downpayment') and line.is_downpayment:
            vals['is_charge_only'] = True
            vals['skip_delivery'] = True

        return vals

    def _reset_baseline(self, flow_lines, sale_line):
        """Reset baseline for reconfirmation.

        Business rule: if the order is cancelled and reconfirmed, the
        reconfirmed values become the new agreed baseline.  Previous
        warnings are cleared.
        """
        subtotal = sale_line.price_unit * sale_line.product_uom_qty * (
            1 - (sale_line.discount or 0.0) / 100.0
        )
        flow_lines.write({
            'confirmed_qty': sale_line.product_uom_qty,
            'confirmed_unit_price': sale_line.price_unit,
            'confirmed_discount': sale_line.discount,
            'confirmed_subtotal': subtotal,
            'confirmed_description': sale_line.name,
            'confirmed_at': fields.Datetime.now(),
            'confirmed_by_id': self.env.uid,
            'current_qty': sale_line.product_uom_qty,
            'unit_price_effective': sale_line.price_unit,
            'state': 'confirmed',
            'was_changed_after_confirmation': False,
            'invoice_warning_level': 'none',
            'change_origin': False,
            'change_note': False,
            'cancelled_qty': 0,
            'last_flow_update_at': fields.Datetime.now(),
            'last_flow_update_by_id': self.env.uid,
        })

    def _reconcile_line_change(self, sale_line, pre_state, flow_lines):
        """Reconcile a sale order line change into linked flow lines.

        Business rules:
          * Do not erase confirmed baseline values after confirmation.
          * Mark changed lines as was_changed_after_confirmation.
          * Preserve original quantities and prices.
          * Adding qty: increase current_qty.
          * Decreasing qty: increase cancelled_qty.
        """
        prec = self.env['decimal.precision'].precision_get('Product Unit of Measure')
        old_qty = pre_state['product_uom_qty']
        new_qty = sale_line.product_uom_qty
        old_price = pre_state['price_unit']
        new_price = sale_line.price_unit
        old_discount = pre_state['discount']
        new_discount = sale_line.discount

        for fl in flow_lines:
            vals = {
                'was_changed_after_confirmation': True,
                'change_origin': 'order',
                'last_flow_update_at': fields.Datetime.now(),
                'last_flow_update_by_id': self.env.uid,
            }

            # Quantity change
            if float_compare(new_qty, old_qty, precision_digits=prec) != 0:
                vals['current_qty'] = new_qty
                if float_compare(new_qty, old_qty, precision_digits=prec) < 0:
                    # Decrease: track cancelled delta
                    delta = old_qty - new_qty
                    vals['cancelled_qty'] = fl.cancelled_qty + delta
                    vals['change_note'] = _(
                        'Quantity decreased from %(old)s to %(new)s',
                        old=old_qty, new=new_qty,
                    )
                else:
                    vals['change_note'] = _(
                        'Quantity increased from %(old)s to %(new)s',
                        old=old_qty, new=new_qty,
                    )

            # Price change
            if float_compare(new_price, old_price, precision_digits=2) != 0:
                vals['unit_price_effective'] = new_price
                note = vals.get('change_note', '')
                price_note = _(
                    'Price changed from %(old)s to %(new)s',
                    old=old_price, new=new_price,
                )
                vals['change_note'] = f"{note}\n{price_note}" if note else price_note

            # Discount change
            if float_compare(new_discount, old_discount, precision_digits=2) != 0:
                note = vals.get('change_note', '')
                disc_note = _(
                    'Discount changed from %(old)s%% to %(new)s%%',
                    old=old_discount, new=new_discount,
                )
                vals['change_note'] = f"{note}\n{disc_note}" if note else disc_note

            fl.with_context(skip_sale_flow_sync=True).write(vals)

            # Recompute warning level
            fl._compute_warning_level()
            fl._update_state()

            # Protection: delivered_qty cannot be reduced below
            if float_compare(fl.delivered_qty, 0, precision_digits=prec) > 0:
                if float_compare(new_qty, fl.delivered_qty, precision_digits=prec) < 0:
                    # Restore: cannot go below delivered
                    sale_line.with_context(skip_sale_flow_sync=True).write({
                        'product_uom_qty': fl.delivered_qty,
                    })
                    fl.with_context(skip_sale_flow_sync=True).write({
                        'current_qty': fl.delivered_qty,
                        'change_note': _(
                            'Quantity capped at delivered qty %(qty)s',
                            qty=fl.delivered_qty,
                        ),
                    })

    def _handle_line_deletion(self, sale_line, flow_line):
        """Handle deletion of a sale line that has logistic history.

        Business rule: if logistic history exists, do not hard-delete.
        Treat as quantity decrease to zero and preserve historical data.
        """
        flow_line.with_context(skip_sale_flow_sync=True).write({
            'current_qty': 0,
            'cancelled_qty': flow_line.current_qty,
            'was_changed_after_confirmation': True,
            'change_origin': 'order',
            'change_note': _('Order line deleted — treated as cancellation'),
            'state': 'cancelled',
            'last_flow_update_at': fields.Datetime.now(),
            'last_flow_update_by_id': self.env.uid,
        })
        flow_line._compute_warning_level()

    def _create_flow_line_from_delivery(self, move):
        """Create a flow line for a product added during delivery.

        Business rule: products added during picking that have no
        corresponding sale order line get a flow line with:
          confirmed_qty = 0
          current_qty = added quantity
          added_during_delivery = True
          warning = orange (by default)

        By default, a sale order line is also created so the product
        appears on the invoice.  If the company setting
        'sale_flow_skip_invoice_logistics' is enabled, no sale order
        line is created and the product stays internal only.
        """
        picking = move.picking_id
        order = picking.sale_id if picking else False
        if not order:
            return self.env['sale.flow.line']

        # Detect rental status from the product itself (rent_periodicity) or from
        # the order being a rental order.  A rentable product delivered
        # on a rental order is a rental item that must come back.
        is_rental = getattr(move.product_id, 'rent_periodicity', False)
        product = move.product_id
        qty = move.quantity if move.state == 'done' else move.product_uom_qty

        # Create a sale order line unless the setting says otherwise.
        # This ensures the product appears on the invoice by default.
        #
        # IMPORTANT: use skip_procurement to prevent _action_launch_stock_rule
        # from creating a duplicate delivery order.  The product was already
        # delivered via the current stock move — there is nothing to procure.
        # Without this flag, creating a SOL on a confirmed order triggers
        # procurement → new picking → 0 delivered → loop.
        skip_invoice = order.company_id.sale_flow_skip_invoice_logistics
        sale_line = False
        if not skip_invoice and not is_rental:
            sale_line = self.env['sale.order.line'].with_context(
                skip_sale_flow_sync=True,
                skip_procurement=True,
            ).create({
                'order_id': order.id,
                'product_id': product.id,
                'product_uom_qty': qty,
                'price_unit': product.list_price,
                'name': _('%(product)s (added during delivery)',
                           product=product.display_name),
            })
            # Link the stock move to this new sale line.
            move.with_context(skip_sale_flow_sync=True).write({
                'sale_line_id': sale_line.id,
            })
            # Set qty_delivered manually.  The standard stock_move
            # computation does not work here because on rental orders
            # the move destination is an internal "Rental" location,
            # not a customer location.  Odoo's _get_outgoing_incoming_moves
            # only counts moves to customer locations.  Since the move
            # is already done, the delivered quantity is a known fact.
            sale_line.with_context(skip_sale_flow_sync=True).write({
                'qty_delivered_method': 'manual',
                'qty_delivered': qty,
            })

        visible = bool(sale_line)

        return self.env['sale.flow.line'].create({
            'name': product.display_name,
            'sale_order_id': order.id,
            'sale_line_id': sale_line.id if sale_line else False,
            'product_id': product.id,
            'product_uom_id': move.uom_id.id,
            'confirmed_qty': 0,
            'current_qty': qty,
            'delivered_qty': move.quantity if move.state == 'done' else 0,
            'unit_price_effective': product.list_price if sale_line else 0,
            'is_rental': is_rental,
            'is_sale': not is_rental,
            'state': 'delivered' if move.state == 'done' else 'confirmed',
            'added_during_delivery': True,
            'added_after_confirmation': True,
            'was_changed_after_confirmation': True,
            'visible_to_customer': visible,
            'invoice_warning_level': 'orange',
            'change_origin': 'delivery',
            'change_note': _('Added during delivery on picking %s', picking.name),
            'last_flow_update_at': fields.Datetime.now(),
            'last_flow_update_by_id': self.env.uid,
        })
