from . import test_rental_set
from . import test_rental_availability
from . import test_rental_availability_warehouse
from . import test_rental_reservation_short_delivery
from . import test_rental_return_operation_date
from . import test_rental_transfer_grounding
from . import test_rental_availability_batch
from . import test_rental_availability_perf
from . import test_rental_on_option
from . import test_rental_set_customer_detail
from . import test_rental_set_ui
